name: deployment pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  # cancelar workflow anterior
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{ github.token }}

  # run linter
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v4
  #       with:
  #         cache: "npm"
  #         node-version: "16"
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Lint
  #       run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  # test:
  #   needs: [lint, build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v4
  #       with:
  #         cache: "npm"
  #         node-version: "16"
  #     - name: Install dependencies
  #       run: npm ci
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: dist
  #         path: dist
  #     - name: Test
  #       run: npm test

  # TODO DEPLOY CON SSH
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ventaspro && git pl && pm2 restart skclient skadmin skserver
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}
          privateKey: ${{ secrets.KEY_SSH }}










      # - uses: appleboy/ssh-action@v1.0.3
      #   name: executing remote ssh commands using password
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     key: ${{ secrets.KEY_SSH }}
      #     port: ${{ secrets.PORT }}
      #     script: cd ventaspro && git pl && pm2 restart skclient skadmin skserver










      # - uses: actions/checkout@v4
      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest
      # - name: Pull Vercel Environment Information
      #   run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Build Project Artifacts
      #   run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      # - name: Deploy Project Artifacts to Vercel
      #   run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
  